GET http://localhost:8743/v1/api/client
Accept: application/json

####

GET http://localhost:8743/v1/api/client/5
Accept: application/json

####

POST http://localhost:8743/v1/api/client
Content-Type: application/json

{
  "name": "Diego",
  "lastname": "Sanchez Luna",
  "email": "disan@gmail.com",
  "phone": "79011432",
  "addressId": 3
}



####
DELETE http://localhost:8743/v1/api/client/7
Content-Type: application/json
####

GET http://localhost:8743/v1/api/client/details
Accept: application/json

####
PUT http://localhost:7000/v1/api/client/25
Content-Type: application/json

{
  "name": "Diego Armando",
  "lastname": "Sanchez Luna",
  "email": "disan@gmail.com",
  "phone": "79011432",
  "addressId": 3
}

####