GET http://localhost:8743/v1/api/client
Accept: application/json

####

GET http://localhost:8743/v1/api/client/5
Accept: application/json

####

POST http://localhost:8743/v1/api/client
Content-Type: application/json

{
  "name": "Ricardo",
  "lastname": "Sornoza",
  "email": "ricsor@gmail.com",
  "phone": "79011432",
  "addressId": 3
}

####
DELETE http://localhost:8743/v1/api/client/7
Content-Type: application/json
